# Automatically generated by Updater v1.0
# @author Daniel J. Finnegan

import shutil, os, os.path, sys
from subprocess import call

if __name__ == '__main__':
	shutil.rmtree('bin', ignore_errors=True)
	shutil.rmtree('build', ignore_errors=True)
	os.mkdir('bin')
	os.chdir('bin')
	call(['cmake', '..', '-G', 'Visual Studio 14 2015 Win64']) # You will have to change this depending on your version of Visual Studio
	call(['cmake', '--build', '.', '--target', 'INSTALL'])
