/**
	Automatically generated by Updater v1.0
	@author Daniel J. Finnegan
*/

#include <iostream>
#include "NumberComputer.hpp"

int main(int argc, char **argv)
{
	int a = 5;
	int b = 6;
	NumberComputer myComputer(a, b);

	int result = myComputer.computeNumber();

	std::cout << "The result is: " << result << std::endl;
	return 0;
}
